project:
  type: website
  output-dir: docs

website:
  title: "Delta-Science-Blog"
  navbar:
    right:
      - about.qmd
      - icon: house-heart
        href: https://delta-science.eu
      - icon: linkedin
        href: https://www.linkedin.com/in/gernot-g-supp-3288933a/  
      - icon: github
        href: https://github.com/GG-Delta
  page-footer:
    left: "Blog made with [Quarto](https://quarto.org/) and the caring wisdom of its community: ğŸ¤ Thank you! ğŸ™"
      
format:
  html:
    theme: solar
    css: styles.css

editor: visual
comments:
  giscus: 
    repo: GG-Delta/Delta-Science-Blog 

